### ISSUE TITLE
Consider having probe endpoints for Quarkus functions similar to functions deployed in other runtimes (Go, Python, node)

### ISSUE THREAD

**Issue by jrangelramos** [boson-project/func#330]
Functions created and deployed using Quarkus runtimes does not contains similar Readiness and Liveness probe URL as other functions created in Node, Python and Go.

Go, Python, Node probe endpoints
``` 
livenessProbe:
  httpGet:
    path: /health/liveness
readinessProbe:
  httpGet:
    path: /health/readiness
```

Quarkus
```
readinessProbe:
  successThreshold: 1
  tcpSocket:
    port: 0
```

Consider having similar probe endpoints to unify experience across languages
